[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "3.1.3"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }